# Generated by Django 4.2.27 on 2026-01-18 15:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('room_name', models.CharField(max_length=64)),
                ('room_capacity', models.IntegerField()),
                ('is_booked', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('slot_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('day', models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('rollno', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('student_name', models.CharField(max_length=100)),
                ('student_dept', models.CharField(max_length=64)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('booking_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='roomalloc.student')),
                ('booking_room', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='roomalloc.room')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='roomalloc.slot')),
            ],
        ),
    ]
