# Generated by Django 4.2.27 on 2026-01-26 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roomalloc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='is_booked',
        ),
    ]
