# Generated by Django 4.2.27 on 2026-01-26 16:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("roomalloc", "0002_remove_room_is_booked"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="slot",
            name="end_time",
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name="slot",
            name="start_time",
            field=models.TimeField(),
        ),
    ]
